openapi: 3.0.1
info:
  title: Leilao SLE
  description: API usando Micronaut
  version: "1.0"
paths:
  /auctions/all-auctions:
    get:
      tags:
      - Auctions
      operationId: listAuctions
      responses:
        "200":
          description: listAuctions 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Auction'
  /auctions/create:
    post:
      tags:
      - Auctions
      operationId: createAuction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auction'
        required: true
      responses:
        "200":
          description: createAuction 200 response
          content:
            application/json:
              schema:
                type: object
  /auctions/find-by-category:
    get:
      tags:
      - Auctions
      operationId: getAuction
      parameters:
      - name: category
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: getAuction 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Auction'
  /auctions/{auction_id}:
    put:
      tags:
      - Auctions
      operationId: updateAuction
      parameters:
      - name: auction_id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auction'
        required: true
      responses:
        "200":
          description: updateAuction 200 response
          content:
            application/json:
              schema:
                type: object
    delete:
      tags:
      - Auctions
      operationId: deleteAuction
      parameters:
      - name: auction_id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: deleteAuction 200 response
          content:
            application/json:
              schema:
                type: object
  /clients/create:
    post:
      tags:
      - Clients
      operationId: createClient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
        required: true
      responses:
        "201":
          description: createClient 201 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
  /clients/list:
    get:
      tags:
      - Clients
      operationId: listClient
      responses:
        "200":
          description: listClient 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
  /clients/{id_client}:
    get:
      tags:
      - Clients
      operationId: getClient
      parameters:
      - name: id_client
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: getClient 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
    put:
      tags:
      - Clients
      operationId: updateClient
      parameters:
      - name: id_client
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
        required: true
      responses:
        "200":
          description: updateClient 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
    delete:
      tags:
      - Clients
      operationId: deleteClient
      parameters:
      - name: id_client
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: deleteClient 204 response
  /devices/available-devices:
    get:
      tags:
      - Devices
      operationId: findAllDevices
      responses:
        "200":
          description: findAllDevices 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComputingDeviceDTO'
  /devices/delete-device/{id}:
    delete:
      tags:
      - Devices
      operationId: deleteDeviceById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: deleteDeviceById 200 response
          content:
            application/json:
              schema:
                type: object
  /devices/find-by-category/{category}:
    get:
      tags:
      - Devices
      operationId: findByCategory
      parameters:
      - name: category
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: findByCategory 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComputingDeviceDTO'
  /devices/register-device:
    post:
      tags:
      - Devices
      operationId: registerDevice
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComputingDevice'
        required: true
      responses:
        "200":
          description: registerDevice 200 response
          content:
            application/json:
              schema:
                type: object
  /devices/update-device/{id}:
    put:
      tags:
      - Devices
      operationId: updateDevice
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                device:
                  $ref: '#/components/schemas/ComputingDevice'
        required: true
      responses:
        "200":
          description: updateDevice 200 response
          content:
            application/json:
              schema:
                type: object
  /financialInstitution/financial-institution:
    get:
      tags:
      - Financial Institutions
      operationId: findFinancialInstitution
      responses:
        "200":
          description: findFinancialInstitution 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FinancialInstitution'
  /financialInstitution/register-fi:
    post:
      tags:
      - Financial Institutions
      operationId: createFI
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FinancialInstitution'
        required: true
      responses:
        "200":
          description: createFI 200 response
          content:
            application/json:
              schema:
                type: object
  /financialInstitution/{id}:
    get:
      tags:
      - Financial Institutions
      operationId: getFinancialInstitution
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: getFinancialInstitution 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialInstitution'
    put:
      tags:
      - Financial Institutions
      operationId: updateFI
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FinancialInstitution'
        required: true
      responses:
        "200":
          description: updateFI 200 response
          content:
            application/json:
              schema:
                type: object
    delete:
      tags:
      - Financial Institutions
      operationId: deleteFI
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: deleteFI 200 response
          content:
            application/json:
              schema:
                type: object
  /vehicles/available-vehicle:
    get:
      tags:
      - Vehicles
      operationId: findAllVehicle
      responses:
        "200":
          description: findAllVehicle 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleDTO'
  /vehicles/delete-vehicle/{id}:
    delete:
      tags:
      - Vehicles
      operationId: deleteVehicle
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: deleteVehicle 200 response
          content:
            application/json:
              schema:
                type: object
  /vehicles/find-vehicle/{id}:
    get:
      tags:
      - Vehicles
      operationId: getVehicle
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: getVehicle 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleDTO'
  /vehicles/register-vehicle:
    post:
      tags:
      - Vehicles
      operationId: createVehicle
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vehicle'
        required: true
      responses:
        "200":
          description: createVehicle 200 response
          content:
            application/json:
              schema:
                type: object
  /vehicles/update-vehicle/{id}:
    put:
      tags:
      - Vehicles
      operationId: updateVehicle
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                vehicle:
                  $ref: '#/components/schemas/Vehicle'
        required: true
      responses:
        "200":
          description: updateVehicle 200 response
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    Auction:
      type: object
      properties:
        auctionId:
          type: integer
          format: int64
          nullable: true
        numAuction:
          type: integer
          format: int32
        status:
          type: string
        occurrenceDate:
          type: string
          format: date
        occurrenceHour:
          type: string
          format: partial-time
        visitDate:
          type: string
          format: date
        visitHour:
          type: string
          format: partial-time
        address:
          type: string
        category:
          type: string
        bids:
          type: array
          items:
            $ref: '#/components/schemas/Bid'
        fInstitutions:
          type: array
          items:
            $ref: '#/components/schemas/FinancialInstitution'
        product:
          nullable: true
          allOf:
          - $ref: '#/components/schemas/Product'
    Bid:
      type: object
      properties:
        bid_id:
          type: integer
          format: int64
          nullable: true
        bid_value:
          type: number
          format: double
        date:
          type: string
          format: date-time
        clients:
          nullable: true
          allOf:
          - $ref: '#/components/schemas/Client'
        auction:
          nullable: true
          allOf:
          - $ref: '#/components/schemas/Auction'
    Client:
      type: object
      properties:
        id_client:
          type: integer
          format: int64
          nullable: true
        name:
          type: string
        email:
          type: string
        cpf:
          type: string
        digitalCertificate:
          type: string
        bids:
          type: array
          items:
            $ref: '#/components/schemas/Bid'
    ComputingDevice:
      required:
      - antenna
      - brand
      - category
      - description
      - id
      - initialValue
      - name
      - ports
      - product
      - productSpecification
      - quantity
      - screenSize
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        name:
          type: string
        quantity:
          type: integer
          format: int32
        category:
          type: string
        description:
          type: string
        brand:
          type: string
        initialValue:
          type: number
          format: double
        ports:
          type: string
        productSpecification:
          type: string
        screenSize:
          type: string
        antenna:
          type: boolean
        product:
          nullable: true
          allOf:
          - $ref: '#/components/schemas/Product'
    ComputingDeviceDTO:
      type: object
      properties:
        name:
          type: string
        quantity:
          type: integer
          format: int32
        category:
          type: string
        description:
          type: string
        brand:
          type: string
        initialValue:
          type: number
          format: double
        ports:
          type: string
        productSpecification:
          type: string
        screenSize:
          type: string
        antenna:
          type: boolean
    FinancialInstitution:
      type: object
      properties:
        fi_id:
          type: integer
          format: int64
          nullable: true
        cnpj:
          type: string
        name:
          type: string
        address:
          type: string
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        devices:
          type: array
          items:
            $ref: '#/components/schemas/ComputingDevice'
        vehicles:
          type: array
          items:
            $ref: '#/components/schemas/Vehicle'
        auction:
          nullable: true
          allOf:
          - $ref: '#/components/schemas/Auction'
    Vehicle:
      required:
      - brand
      - category
      - color
      - description
      - id
      - initialValue
      - manufactureYear
      - model
      - product
      - resultPrecautionaryExpertise
      - sunroof
      - tractionType
      - yearLicensing
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        brand:
          type: string
        manufactureYear:
          type: string
        model:
          type: string
        description:
          type: string
        color:
          type: string
        initialValue:
          type: number
          format: double
        category:
          type: string
        yearLicensing:
          type: integer
          format: int32
        resultPrecautionaryExpertise:
          type: string
        tractionType:
          type: string
        sunroof:
          type: boolean
        product:
          nullable: true
          allOf:
          - $ref: '#/components/schemas/Product'
    VehicleDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        brand:
          type: string
        manufactureYear:
          type: string
        model:
          type: string
        description:
          type: string
        color:
          type: string
        initialValue:
          type: number
          format: double
        category:
          type: string
        yearLicensing:
          type: integer
          format: int32
        resultPrecautionaryExpertise:
          type: string
        tractionType:
          type: string
        sunroof:
          type: boolean
