openapi: 3.0.1
paths:
  /dispositivos/switches/create:
    post:
      operationId: criarSwitch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Switch'
        required: true
      responses:
        "201":
          description: criarSwitch 201 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DispositivoInformaticaDTO'
  /dispositivos/switches/list:
    get:
      operationId: listarSwitches
      responses:
        "200":
          description: listarSwitches 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DispositivoInformaticaDTO'
  /dispositivos/switches/{id}:
    get:
      operationId: getSwitches
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: getSwitches 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DispositivoInformaticaDTO'
    delete:
      operationId: deletarSwitch
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: deletarSwitch 204 response
components:
  schemas:
    DispositivoInformatica:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        name:
          type: string
        quantity:
          type: integer
          format: int32
        description:
          type: string
        deviceValue:
          type: number
          format: double
        brand:
          type: string
    DispositivoInformaticaDTO:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/DispositivoInformatica'
        quantity:
          $ref: '#/components/schemas/DispositivoInformatica'
        description:
          $ref: '#/components/schemas/DispositivoInformatica'
        deviceValue:
          $ref: '#/components/schemas/DispositivoInformatica'
        brand:
          $ref: '#/components/schemas/DispositivoInformatica'
        ports:
          type: string
        volts:
          type: string
        specification:
          type: string
        antenna:
          type: boolean
        screenSize:
          type: string
        refreshRate:
          type: string
        numberOfPorts:
          type: integer
          format: int32
        firmwareVersion:
          type: string
    Switch:
      type: object
      allOf:
      - $ref: '#/components/schemas/DispositivoInformatica'
      - properties:
          numberOfPorts:
            type: integer
            format: int32
          firmwareVersion:
            type: string
