openapi: 3.0.1
paths:
  /clients/create:
    post:
      operationId: createClient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
        required: true
      responses:
        "201":
          description: createClient 201 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
  /clients/list:
    get:
      operationId: listarClient
      responses:
        "200":
          description: listarClient 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
  /clients/{id}:
    get:
      operationId: getClient
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: getClient 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
    delete:
      operationId: deletarClient
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: deletarClient 204 response
components:
  schemas:
    Client:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        cpf:
          type: string
        digitalCertificate:
          type: string
